import {
  Dumbbell,
  Flame,
  HeartPulse,
  Apple,
  Brain,
  Moon,
  Swords,
  StretchHorizontal,
  BookOpen,
  Video,
  FileText,
  Activity,
  Flower2,
  Pill,
  type LuIcon,
} from 'lucide-react'

export type ResourceType = 'Guide' | 'Video' | 'Article' | 'Drill'
export type ResourceCategory =
  | 'Strength'
  | 'Conditioning'
  | 'Mobility'
  | 'Nutrition'
  | 'Recovery'
  | 'Mindset'
  | 'Wrestling'
  | 'Fat Loss'
  | 'Yoga'
  | 'Supplements'

export type Resource = {
  id: string
  title: string
  category: ResourceCategory
  type: ResourceType
  level: 'Beginner' | 'Intermediate' | 'Advanced' | 'All'
  duration: string
  blurb: string
  body: string
  free: true
}

export const categoryMeta: Record<
  ResourceCategory,
  { icon: LuIcon; color: string }
> = {
  Strength: { icon: Dumbbell, color: '#e0a93a' },
  Conditioning: { icon: Flame, color: '#d6452a' },
  Mobility: { icon: StretchHorizontal, color: '#e0c14a' },
  Nutrition: { icon: Apple, color: '#7fb069' },
  Recovery: { icon: Moon, color: '#8a8fd6' },
  Mindset: { icon: Brain, color: '#c97ae0' },
  Wrestling: { icon: Swords, color: '#d6452a' },
  'Fat Loss': { icon: Activity, color: '#e0a93a' },
  Yoga: { icon: Flower2, color: '#7fb069' },
  Supplements: { icon: Pill, color: '#c97ae0' },
}

export const typeMeta: Record<ResourceType, { icon: LuIcon; label: string }> = {
  Guide: { icon: BookOpen, label: 'Guide' },
  Video: { icon: Video, label: 'Video' },
  Article: { icon: FileText, label: 'Article' },
  Drill: { icon: Activity, label: 'Drill' },
}

export const resources: Resource[] = [
  {
    id: 'r1',
    title: 'The Pehlwan Foundation: 5 Compound Lifts',
    category: 'Strength',
    type: 'Guide',
    level: 'Beginner',
    duration: '12 min read',
    blurb: 'Master the squat, deadlift, press, row and pull-up — the bedrock of every Dangal athlete.',
    body: `The five compound lifts recruit the most muscle, build raw strength and translate directly to the mat and to life.\n\n1. Back Squat — 5x5, add 2.5kg weekly. Depth: hip crease below knee.\n2. Conventional Deadlift — 3x3 heavy. Brace, push the floor, lock out hips.\n3. Overhead Press — 5x5. Strict, no leg drive.\n4. Pendlay Row — 5x5. Explosive from the floor.\n5. Pull-up — 3xAMRAP. Add weight once you hit 10 clean reps.\n\nRun this 3x/week, eat in a slight surplus, sleep 8h. In 12 weeks you will be unrecognisable.`,
    free: true,
  },
  {
    id: 'r2',
    title: 'Desi Akhada Conditioning Circuit',
    category: 'Conditioning',
    type: 'Drill',
    level: 'Intermediate',
    duration: '20 min',
    blurb: 'A wrestling-inspired metabolic circuit using a gada (mace), bag and bodyweight — torch fat, forge engine.',
    body: `Warm up 5 min. Then 4 rounds, 45s work / 15s rest:\n- Gada swing (or kettlebell swing)\n- Sprawl to jump\n- Bag clean + push press\n- Mountain climbers\n- Shadow wrestling shots\n\nFinish with 100 burpees for time (cap 12 min). This is the akhada burn — the mental grit you build here shows up everywhere.`,
    free: true,
  },
  {
    id: 'r3',
    title: 'Daily Mobility Ritual for Lifters',
    category: 'Mobility',
    type: 'Guide',
    level: 'All',
    duration: '10 min',
    blurb: 'Bulletproof hips, shoulders and spine with this 10-minute daily flow. Do it before every session.',
    body: `1. Cat-cow x10\n2. World\'s greatest stretch x5 each side\n3. 90/90 hip switches x10\n4. Wall ankle dorsiflexion x10 each\n5. Band pull-aparts x20\n6. Thoracic bridge x8 each\n7. Goblet squat hold 60s\n\nConsistency over intensity. Two weeks daily and your lifts will move better and pain will fade.`,
    free: true,
  },
  {
    id: 'r4',
    title: 'The Dangal Plate: Desi Nutrition on a Budget',
    category: 'Nutrition',
    type: 'Article',
    level: 'All',
    duration: '8 min read',
    blurb: 'Build a champion\'s body with everyday Indian food — dal, chana, paneer, rice and ghee, done right.',
    body: `Protein target: 1.6–2.2g per kg bodyweight. Hit it cheap with:\n- Chana (soaked/sprouted): 19g/cup\n- Paneer: 18g/100g\n- Soya chunks: 52g/100g\n- Eggs: 6g each\n- Chicken: 31g/100g\n- Whey: 25g/scoop\n\nCarbs: rice, roti, oats, banana — fuel training.\nFats: ghee, peanut, almond — moderate.\n\nEat 4 meals, front-load carbs around training. Hydrate 3–4L. This is sustainable, cheap and brutal-effective.`,
    free: true,
  },
  {
    id: 'r5',
    title: 'Sleep as a Performance Drug',
    category: 'Recovery',
    type: 'Article',
    level: 'All',
    duration: '6 min read',
    blurb: 'Sleep is the most anabolic thing you can do. Here\'s how to engineer 8 hours that build muscle.',
    body: `Sleep is when growth hormone peaks, muscle repairs and the CNS resets. Skimping it sabotages every rep.\n\n- Fixed sleep/wake time, even weekends.\n- Last meal 2h before bed, lower carbs.\n- No screens 60 min prior; dim lights.\n- Cool, dark, quiet room (18–20°C).\n- Magnesium glycinate 30 min prior if deficient.\n\nAim 7–9h. Track HRV if you can. You will lift heavier, recover faster and think sharper.`,
    free: true,
  },
  {
    id: 'r6',
    title: 'The Pehlwan Mindset: Discipline over Motivation',
    category: 'Mindset',
    type: 'Article',
    level: 'All',
    duration: '7 min read',
    blurb: 'Motivation fades; discipline is forged. The mental code of the akhada, adapted for modern life.',
    body: `The akhada teaches: you don\'t train when you feel like it. You train because it is who you are.\n\n1. Identity over outcome — "I am someone who trains."\n2. Show up on the hard days, especially then.\n3. Win the morning — train first if possible.\n4. Track everything; what gets measured improves.\n5. Surround yourself with people who raise the bar.\n\nDiscipline is a muscle. Rep it daily.`,
    free: true,
  },
  {
    id: 'r7',
    title: 'Wrestling Shots & Sprawl Mechanics',
    category: 'Wrestling',
    type: 'Drill',
    level: 'Intermediate',
    duration: '15 min',
    blurb: 'Learn the penetration step and sprawl — the foundation of takedown offence and defence.',
    body: `Penetration step:\n- Drop level, lead foot steps deep between opponent\'s feet.\n- Trail leg drives, head up, back straight.\n- Hands secure the leg, drive through.\n\nSprawl:\n- Opponent shoots — hips shoot back, legs back.\n- Chest on their back, heavy.\n- Spin behind for 2.\n\nDrill: 3x30s shadow shots, 3x15 sprawals, 2x live pummelling. Daily for 2 weeks for crisp mechanics.`,
    free: true,
  },
  {
    id: 'r8',
    title: 'Cutting Fat Without Losing Muscle',
    category: 'Fat Loss',
    type: 'Guide',
    level: 'Intermediate',
    duration: '10 min read',
    blurb: 'A sustainable deficit that protects strength. No crash diets, no cardio suicide.',
    body: `1. Set deficit: 300–500 kcal below maintenance.\n2. Protein high: 2.2g/kg minimum.\n3. Keep lifting heavy — intensity up, volume managed.\n4. Add 8–10k steps daily (NEAT is king).\n5. 2–3 conditioning sessions, Z2 cardio.\n6. Re-feed every 5–7 days at maintenance.\n\nLose 0.5–1% bodyweight/week. Faster = muscle loss. Patience wins.`,
    free: true,
  },
  {
    id: 'r9',
    title: 'The Gada (Mace) Swing Primer',
    category: 'Strength',
    type: 'Video',
    level: 'Advanced',
    duration: '8 min',
    blurb: 'The ancient pehlwan tool for shoulder strength, core and grip. Learn the 10-to-2 swing safely.',
    body: `The gada builds the shoulders, core and grip like nothing else.\n\nSetup: stance wide, mace head behind one shoulder, hands stacked.\nSwing: drive hips, let momentum carry the head over the head to the opposite shoulder. Control the catch.\n\nStart light (4–6kg). 3x10 each side. Build to 360s (full circles). Train 2x/week. Your shoulders will thank you in 6 weeks.`,
    free: true,
  },
  {
    id: 'r10',
    title: 'Breathwork for Power & Calm',
    category: 'Mindset',
    type: 'Drill',
    level: 'All',
    duration: '8 min',
    blurb: 'Box breathing to steady the mind, power breaths to brace heavy lifts. Two protocols, big payoff.',
    body: `Box breathing (pre-session calm): inhale 4s, hold 4s, exhale 4s, hold 4s. 4 minutes. Lowers HR, sharpens focus.\n\nPower breath (brace): sharp exhale + full brace before every heavy rep. Protects spine, increases force.\n\nRecovery breath (post-set): long slow exhale through nose, 6s, to drop HR between sets.\n\nMaster your breath, master your training.`,
    free: true,
  },
  {
    id: 'r11',
    title: 'Joint-Friendly Hypertrophy for Beginners',
    category: 'Strength',
    type: 'Guide',
    level: 'Beginner',
    duration: '9 min read',
    blurb: 'Build muscle with lifts that love your joints — perfect for first 6 months in the gym.',
    body: `Use higher reps (8–15), controlled tempo, full range.\n\n- Goblet squat 3x10\n- DB press 3x10\n- DB row 3x12\n- RDL 3x10\n- Lat pulldown 3x12\n- Plank 3x45s\n\n3x/week, add reps then weight. Eat protein. Sleep. Joints adapt, muscle grows, no injuries. Graduate to barbell lifts in 8–12 weeks.`,
    free: true,
  },
  {
    id: 'r12',
    title: 'Hydration & Electrolytes Explained',
    category: 'Nutrition',
    type: 'Article',
    level: 'All',
    duration: '5 min read',
    blurb: '2% dehydration = 10% strength drop. The simple protocol to stay fuelled and cramp-free.',
    body: `Drink 500ml on waking. 250–500ml per hour through the day. Add a pinch of salt + lemon to one bottle in heat or heavy sweat.\n\nPre-training: 400ml 2h prior. During: 150–250ml every 15 min for sessions over 60 min. Post: weigh yourself, drink 1.5x lost kg.\n\nElectrolytes matter in long/hot sessions — sodium, potassium, magnesium. Cramps? You\'re likely under-fuelled, not weak.`,
    free: true,
  },
  // ===== New vast resources =====
  {
    id: 'r13',
    title: 'The Bench Press Bible: Setup, Grip, Leg Drive',
    category: 'Strength',
    type: 'Guide',
    level: 'Intermediate',
    duration: '11 min read',
    blurb: 'Master the bench: eye under bar, full-foot leg drive, controlled descent, explosive press.',
    body: `SETUP\n1. Lie flat, eyes directly under the bar.\n2. Retract shoulder blades — pinch them together and down.\n3. Plant feet flat, hips on bench, arch neutral (not excessive).\n4. Grip: thumbs around bar, ~1.5x shoulder width.\n\nEXECUTION\n- Unrack with lats, not chest.\n- Lower under control to lower-chest/nipple line (2-3s).\n- Elbows ~45°, not flared.\n- Drive feet into floor (leg drive) as you press up and slightly back.\n- Lock out over shoulders, not over face.\n\nCommon fixes: bar drifting over face = weak lats; hips lifting = too much leg drive; wrists bent = grip too high. Film yourself from the side.`,
    free: true,
  },
  {
    id: 'r14',
    title: 'Tabata & Metcon Protocols Explained',
    category: 'Conditioning',
    type: 'Drill',
    level: 'Intermediate',
    duration: '12 min',
    blurb: '4-minute Tabata, EMOMs, AMRAPs — the conditioning toolkit that fits any schedule.',
    body: `TABATA — 20s max effort / 10s rest × 8 rounds = 4 min. Brutal, effective. Pick one movement (bike, row, burpee, kettlebell swing).\n\nEMOM (Every Minute On the Minute) — do X reps at the top of each minute, rest the remainder. e.g. 10-min EMOM of 15 kettlebell swings.\n\nAMRAP (As Many Rounds As Possible) — set a time cap, complete a circuit as many times as you can. e.g. 12-min AMRAP: 10 push-ups, 15 squats, 200m run.\n\nUse 2-3 conditioning sessions/week. Track your output (reps, rounds, distance) to measure progress. Warm up 5 min, cool down 5 min always.`,
    free: true,
  },
  {
    id: 'r15',
    title: 'Fix Your Squat Depth & Buttwink',
    category: 'Mobility',
    type: 'Article',
    level: 'All',
    duration: '7 min read',
    blurb: 'Can\'t hit depth? Lower back rounding at the bottom? Here are the real fixes.',
    body: `PROBLEM 1: Can\'t reach depth (hips below knees)\nCauses: tight calves/ankles, tight hips, weak glutes.\nFixes: ankle dorsiflexion drills (wall stretches, banded joint distraction), 90/90 hip switches, goblet squats paused at bottom.\n\nPROBLEM 2: Buttwink (pelvis tucks under at bottom)\nCauses: tight hamstrings, limited hip flexion, core weakness.\nFixes: hamstring stretching (RDLs, toe touches), deep squat holds with counterbalance, strengthen core with dead bugs.\n\nPROBLEM 3: Knees caving (valgus)\nFixes: banded squats (band around knees, push out), glute activation (clamshells, lateral walks), cue "spread the floor".\n\nFilm from the side. Improve 1 thing at a time. Depth comes with practice + mobility.`,
    free: true,
  },
  {
    id: 'r16',
    title: 'Pre-Workout Nutrition: What & When to Eat',
    category: 'Nutrition',
    type: 'Guide',
    level: 'All',
    duration: '6 min read',
    blurb: 'Time your carbs and protein right to train hard without crashing.',
    body: `2-3 HOURS BEFORE (full meal)\n- Carbs: rice, roti, oats, banana (fuel)\n- Protein: chicken, eggs, paneer, whey (protect muscle)\n- Low fat (slows digestion)\n\n30-60 MIN BEFORE (top-up, optional)\n- Fast carbs: banana, dates, or pre-workout drink\n- Small protein: scoop of whey\n- Avoid heavy/fibrous meals (GI discomfort)\n\nDURING (only for sessions >90 min)\n- Sip water + electrolytes\n- BCAAs/intra-carbs optional for endurance\n\nPOST (within 1-2h)\n- Protein 0.4g/kg + carbs 1g/kg\n- e.g. whey + banana, or chicken + rice\n\nListen to your body. Some train fasted fine; others need fuel. Experiment and track how you feel.`,
    free: true,
  },
  {
    id: 'r17',
    title: 'The Complete Recovery Toolkit',
    category: 'Recovery',
    type: 'Guide',
    level: 'All',
    duration: '9 min read',
    blurb: 'Sleep, nutrition, active recovery, sauna, ice, massage — what actually works.',
    body: `TIER 1 (non-negotiables — 80% of results)\n- Sleep 7-9h, fixed schedule. This is when GH peaks and muscle repairs.\n- Protein 1.6-2.2g/kg, evenly across meals.\n- Hydration 3-4L.\n- Caloric balance matching your goal.\n\nTIER 2 (high impact)\n- Active recovery: 20-30 min easy walk/cycle on rest days.\n- Deload week every 4-8 weeks (reduce volume 40-60%).\n- Manage stress (cortisol kills recovery).\n\nTIER 3 (marginal gains — 5-10%)\n- Sauna 15-20 min, 2-3x/week (heat stress adaptation).\n- Cold exposure 2-3 min (reduces DOMS, but blunts hypertrophy if used right after lifting).\n- Foam rolling / massage (blood flow, feels good).\n- Compression, BFR, EMS — minimal evidence.\n\nNail Tier 1 first. Most people skip sleep chasing Tier 3 gadgets. Don\'t be most people.`,
    free: true,
  },
  {
    id: 'r18',
    title: 'Building Unbreakable Discipline',
    category: 'Mindset',
    type: 'Article',
    level: 'All',
    duration: '8 min read',
    blurb: 'Motivation fades. Discipline is a muscle you build with 5 specific practices.',
    body: `1. IDENTITY OVER OUTCOME\n"I am someone who trains" beats "I want to lose 5kg". Identity-based habits stick.\n\n2. THE 2-MINUTE RULE\nScale any habit down to 2 minutes to start. "Put on gym shoes" is the gateway to a full workout.\n\n3. NEVER MISS TWICE\nMissed a day? Don\'t miss the next. One miss is an accident; two is the start of a new (bad) habit.\n\n4. ENVIRONMENT > WILLPOWER\nLay out gym clothes the night before. Keep junk food out of the house. Make the right choice the easy choice.\n\n5. TRACK & STREAK\nVisible progress (checkmarks, streak) reinforces the habit. Don\'t break the chain.\n\nDiscipline isn\'t punishment — it\'s self-respect in action. Show up especially on the hard days. That\'s where champions are built.`,
    free: true,
  },
  {
    id: 'r19',
    title: 'Pehlwani: The Ancient Indian Wrestling Tradition',
    category: 'Wrestling',
    type: 'Article',
    level: 'All',
    duration: '10 min read',
    blurb: 'The history, training and philosophy of the akhada — the soul of Dangal.',
    body: `Pehlwani (or kushti) is the traditional Indian wrestling style, born in the akhada (wrestling pit). Traced back over 1000 years, it blends Malla-yuddha (ancient combat) with Persian influences brought by the Mughals.\n\nTHE AKHADA\n- Trained on red dirt (mitti), mixed with ghee and turmeric for grip and healing.\n- Wrestlers (pehlwans) live a disciplined life: brahmacharya (celibacy/control), vegetarian diet, dawn training.\n\nTRAINING\n- Surya namaskar and dand (Hindu push-ups) — hundreds daily.\n- Bethak (deep-knee squats) — hundreds daily.\n- Gada (mace) swings for shoulder strength.\n- Jori (heavy clubs) for grip and rotation.\n- Live wrestling (dangal) on weekends.\n\nDIET\n- Khurdi (almonds, ghee, milk) for strength.\n- Large midday meal after training.\n- No alcohol, no tobacco.\n\nPHILOSOPHY\nThe pehlwan trains body and character. Strength without discipline is nothing. This is the Dangal code.`,
    free: true,
  },
  {
    id: 'r20',
    title: 'The Lean-Cutting Playbook: 12 Weeks to Shredded',
    category: 'Fat Loss',
    type: 'Guide',
    level: 'Advanced',
    duration: '14 min read',
    blurb: 'A complete 12-week cutting protocol — deficit, macros, training, cardio, refeeds.',
    body: `WEEKS 1-4: ESTABLISH THE DEFICIT\n- Calculate maintenance (TDEE), set 500kcal below.\n- Protein 2.2g/kg, fats 0.8g/kg, rest carbs.\n- Keep lifting heavy — intensity up, volume managed.\n- 8-10k steps daily.\n- Target: 0.5-0.7% bodyweight loss/week.\n\nWEEKS 5-8: TIGHTEN\n- If progress stalls, reduce kcal by 150-200 OR add 2x20min Z2 cardio.\n- Add 1 refeed day at maintenance (carbs up) every 5-7 days.\n- Sleep 8h — cutting is cortisol-heavy.\n- Monitor strength; if it drops hard, eat more.\n\nWEEKS 9-12: PEEL THE LAST LAYER\n- Deficit 300-500kcal (smaller now — less to lose).\n- 3 cardio sessions: 2x Z2, 1x intervals.\n- Protein stays high (2.4g/kg).\n- Expect hunger — volume eat (veg, salads).\n\nPOST-CUT\n- Reverse diet: add 100-150kcal/week back to maintenance.\n- Don\'t binge. Hold maintenance 4-6 weeks before next phase.\n\nGolden rule: patience. Faster = muscle loss + rebound. 12 weeks of discipline beats 6 weeks of suffering.`,
    free: true,
  },
  {
    id: 'r21',
    title: 'Sun Salutation (Surya Namaskar) for Lifters',
    category: 'Yoga',
    type: 'Drill',
    level: 'Beginner',
    duration: '10 min',
    blurb: '12 poses, one flow. The perfect warm-up — opens hips, shoulders, spine and breath.',
    body: `Surya Namaskar (Sun Salutation) is a 12-pose flowing sequence. Do 5-12 rounds as a warm-up.\n\nTHE 12 POSES\n1. Pranamasana (Prayer pose)\n2. Hasta Padasana (Forward fold)\n3. Ashwa Sanchalanasana (Lunge, right leg back)\n4. Dandasana (Plank)\n5. Ashtanga Namaskara (Eight-point/knees-chest-chin)\n6. Bhujangasana (Cobra/upward dog)\n7. Adho Mukha Svanasana (Downward dog)\n8. Ashwa Sanchalanasana (Lunge, right leg forward)\n9. Hasta Padasana (Forward fold)\n10. Hasta Uttanasana (Arms up, arch back)\n11. Pranamasana (Prayer)\n\n(Alternate the lunge leg each round.)\n\nBENEFITS FOR LIFTERS\n- Opens tight hamstrings, hips, shoulders.\n- Mobilises the spine through full range.\n- Wakes up the breath and nervous system.\n- 5 rounds = ~3 min of perfect movement prep.\n\nBreathe with each pose. Inhale on extensions, exhale on folds. Start slow, build flow.`,
    free: true,
  },
  {
    id: 'r22',
    title: 'Supplements 101: What Works, What\'s Hype',
    category: 'Supplements',
    type: 'Guide',
    level: 'All',
    duration: '10 min read',
    blurb: 'Whey, creatine, caffeine, multivitamin — the few that actually deliver. Skip the rest.',
    body: `TIER 1 (evidence-backed, worth it)\n- CREATINE MONOHYDRATE: 5g/day, every day. Most-studied supplement ever. +5-15% power output, lean mass gains. Cheap.\n- WHEY PROTEIN: 25-30g/scoop. Convenient way to hit protein target. Fast absorption.\n- CAFFEINE: 3-6mg/kg pre-workout. Proven performance boost. Don\'t exceed 400mg/day.\n- VITAMIN D3: 1000-4000 IU if you get little sun. Bone, mood, testosterone.\n- OMEGA-3 (EPA/DHA): 1-2g if you don\'t eat fatty fish. Inflammation, heart, brain.\n\nTIER 2 (situational)\n- BETA-ALANINE: 3-6g/day for high-rep/interval work (tingles = normal).\n- CITRULLINE: 6-8g pre-workout for pumps/blood flow.\n- MAGNESIUM: glycinate before bed if deficient (sleep, cramps).\n- ZINC: 15-30mg if deficient (testosterone, immunity).\n\nTIER 3 (mostly hype)\n- BCAAs (redundant if protein is adequate)\n- Testosterone boosters (Tribulus, fenugreek — minimal evidence)\n- "Mass gainers" (just sugar + protein; eat real food)\n- Fat burners (caffeine + garbage)\n\nRULE: supplements supplement. Food, sleep and training are 95%. Don\'t major in the minors.`,
    free: true,
  },
  {
    id: 'r23',
    title: 'Desk Worker\'s Mobility Rescue Routine',
    category: 'Mobility',
    type: 'Drill',
    level: 'All',
    duration: '8 min',
    blurb: 'Sit all day? This 8-minute flow fixes the rounded shoulders, tight hips and stiff back.',
    body: `Do this 1-2x daily (morning + lunch break). Each move 8-10 reps.\n\n1. CHIN TUCKS ×10 — fix forward head.\n2. WALL ANGELS ×10 — open chest, retract shoulders.\n3. CAT-COW ×10 — mobilise spine.\n4. THORACIC ROTATION (kneeling, rotate arm to ceiling) ×8 each side.\n5. 90/90 HIP SWITCHES ×10 — open hips.\n6. SOFA STRETCH (hip flexor) 30s each side.\n7. GLUTE BRIDGE ×15 — wake up sleepy glutes.\n8. CHILD\'S POSE 30s — decompress.\n\nThe biggest issue with sitting is "glute amnesia" + tight hip flexors + rounded upper back. This hits all three. Consistency > intensity. 8 minutes daily beats 1 hour weekly.`,
    free: true,
  },
  {
    id: 'r24',
    title: 'Protein: How Much, When & From What',
    category: 'Nutrition',
    type: 'Article',
    level: 'All',
    duration: '7 min read',
    blurb: 'The only macro that builds muscle. How much you need, best sources, timing myths busted.',
    body: `HOW MUCH\n- General health: 0.8-1.0g/kg bodyweight.\n- Building muscle: 1.6-2.2g/kg.\n- Cutting (preserve muscle): 2.0-2.4g/kg.\n- More than 2.5g/kg shows no extra benefit — save your money.\n\nBEST SOURCES (per 100g)\n- Chicken breast: 31g\n- Soya chunks: 52g\n- Tuna: 30g\n- Paneer: 18g\n- Eggs: 13g (6g per egg)\n- Greek yoghurt: 10g\n- Lentils (cooked): 9g\n- Whey powder: 75-80g (25g per scoop)\n\nTIMING\n- Total daily intake matters most. Don\'t stress the "anabolic window".\n- Aim 20-40g per meal, 4 meals, ~3-4h apart.\n- Pre/post-workout: get 20-40g within a few hours of training.\n\nMYTHS\n- "Plant protein is incomplete" — mostly false; eat variety.\n- "You can only absorb 30g at once" — false; the body handles 50g+ fine, just slower.\n- "More protein = kidney damage" — false in healthy people.\n\nHit your daily target. That\'s 90% of it.`,
    free: true,
  },
  {
    id: 'r25',
    title: 'The Cold Shower & Ice Bath Protocol',
    category: 'Recovery',
    type: 'Drill',
    level: 'All',
    duration: '6 min',
    blurb: 'Cold exposure done right — reduce soreness, build mental grit, boost resilience.',
    body: `WHY COLD?\n- Reduces DOMS (delayed muscle soreness) after hard sessions.\n- Norepinephrine spike — focus, mood.\n- Builds mental toughness (the hard part = choosing to get in).\n\nPROTOCOL (build up gradually)\nWEEK 1-2: End your normal shower with 30s cold. Just 30s.\nWEEK 3-4: 1-2 min cold at the end.\nWEEK 5+: 2-3 min cold, OR dedicated ice bath 3-5 min at 10-15°C.\n\nRULES\n- Breathe. Slow controlled breaths calm the cold shock.\n- Don\'t exceed 5 min. More isn\'t better.\n- Warm up naturally after (hot drink, movement) — not a hot shower.\n\nIMPORTANT CAVEAT FOR LIFTERS\nCold exposure RIGHT AFTER training blunts hypertrophy (it reduces the inflammation that drives growth). Use cold on rest days or 4+ hours after lifting. For pure recovery/athletes (not hypertrophy), post-session is fine.\n\nSkip if: heart condition, pregnant, Raynaud\'s. Listen to your body.`,
    free: true,
  },
  {
    id: 'r26',
    title: 'Pull-up Progression: From Zero to Ten',
    category: 'Strength',
    type: 'Guide',
    level: 'Beginner',
    duration: '9 min read',
    blurb: 'Can\'t do a single pull-up? This step-by-step progression takes you from dead hangs to clean sets of ten.',
    body: `The pull-up is the king of upper-body strength. Most beginners can\'t do one — here\'s the proven path.\n\nSTAGE 1: DEAD HANG (week 1-2)\n- Grip bar shoulder-width, hang with straight arms.\n- Build to 3 sets of 30 seconds.\n- Builds grip, shoulder stability and tendon strength.\n\nSTAGE 2: SCAPULAR PULL-UPS (week 2-3)\n- Hang, then pull shoulder blades down and back (no elbow bend).\n- 3 sets of 8-10 reps.\n\nSTAGE 3: NEGATIVES (week 3-5)\n- Jump or step up to the top position (chin over bar).\n- Lower slowly — aim for 5 seconds down.\n- 3 sets of 3-5 reps.\n\nSTAGE 4: BANDED ASSISTED (week 5-7)\n- Loop a resistance band around the bar and your foot/knee.\n- Use the thickest band first, progress to thinner bands.\n- 3 sets of 5-8 reps.\n\nSTAGE 5: FIRST PULL-UP (week 7-10)\n- Brace, pull elbows down and back, chin over bar.\n- Even one rep counts. Do multiple singles throughout the day.\n\nONCE YOU HIT 1: Grease the groove with multiple sub-max sets daily. Add a rep every week or two. Within 3-6 months you\'ll be doing sets of 5-10.\n\nCommon fixes: don\'t swing (kip), don\'t half-rep, full hang at bottom, chin over bar at top. Quality over quantity always.`,
    free: true,
  },
  {
    id: 'r27',
    title: 'Deadlift Setup: The 5-Step Reset',
    category: 'Strength',
    type: 'Guide',
    level: 'Intermediate',
    duration: '10 min read',
    blurb: 'Set up like a powerlifter: stance, grip, brace, pull the slack, drive. Five steps to a safe, heavy pull.',
    body: `The conventional deadlift rewards perfect setup. Walk through these 5 steps before EVERY rep.\n\nSTEP 1: STANCE\n- Feet hip-width, toes slightly out.\n- Bar over mid-foot (shoelaces). The bar should almost touch your shins.\n\nSTEP 2: GRIP\n- Hinge at hips, bend knees until shins touch the bar.\n- Grip just outside your knees — double overhand for warm-ups, hook or mixed grip for heavy.\n- Arms long and straight, no bent elbows.\n\nSTEP 3: BRACE\n- Big breath into belly (360° expansion, not just stomach).\n- Squeeze lats — think "protect your armpits".\n- Chest up, back flat (neutral spine — not rounded, not over-arched).\n\nSTEP 4: PULL THE SLACK\n- Push the floor away slightly to take tension out of the bar.\n- You should feel the bar "click" against the plates.\n- This eliminates the jerk that causes injuries.\n\nSTEP 5: DRIVE\n- Push the floor away (leg drive first).\n- Hips and chest rise together — don\'t shoot hips first.\n- Lock out by squeezing glutes and standing tall.\n- Lower under control: hips back, then bend knees.\n\nCOMMON MISTAKES\n- Hips too low (squats the weight) or too high (good-mornings it).\n- Rounded lower back — fix with lighter weight and better brace.\n- Bar drifts away from body — keep it grazing your legs the whole way.\n- Jerking off the floor — pull slack first.\n\nFilm yourself from the side. The bar path should be a straight vertical line. Train 1-2x/week, 3-5 working reps, add 2.5kg weekly. Patience beats ego.`,
    free: true,
  },
  {
    id: 'r28',
    title: 'Post-Workout Stretching Routine',
    category: 'Mobility',
    type: 'Drill',
    level: 'All',
    duration: '8 min',
    blurb: 'A targeted 8-minute cool-down that targets the muscles you just trained — restore range, reduce soreness, calm the system.',
    body: `Stretching post-workout (when muscles are warm) improves recovery, restores range of motion and downshifts the nervous system. Hold each stretch 30-45 seconds, both sides, breathe deep.\n\nUPPER BODY DAY\n1. CHEST DOORWAY STRETCH — forearm on doorframe, rotate away.\n2. LAT STRETCH — hang from bar or overhead reach, side-bend.\n3. TRICEPS — pull elbow behind head.\n4. SHOULDERS — cross-arm pull across chest.\n5. NECK — gentle ear-to-shoulder tilts.\n6. WRISTS — flex and extend on the floor.\n\nLOWER BODY DAY\n1. STANDING HAMSTRING — foot on bench, hinge hips, flat back.\n2. QUAD STRETCH — pull heel to glute, knees together.\n3. HIP FLEXOR (SOFA STRETCH) — back knee on floor, front foot forward, squeeze glute.\n4. PIGEON — hip opener, deep glute stretch.\n5. CALF — wall stretch, back leg straight.\n6. CHILD\'S POSE — knees wide, arms forward, forehead to floor.\n\nFULL BODY / CONDITIONING DAY\n- DOWNWARD DOG 30s (calves, hamstrings, shoulders).\n- COBRA/UPWARD DOG 30s (spine, chest).\n- WORLD\'S GREATEST STRETCH each side (hips, thoracic).\n- SEATED FORWARD FOLD 1 min (calm nervous system).\n\nRULES\n- No bouncing — long, slow holds.\n- Mild discomfort, not pain.\n- Breathe deep into the belly — this triggers the parasympathetic recovery response.\n- Don\'t skip. 8 minutes today = better training tomorrow.`,
    free: true,
  },
  {
    id: 'r29',
    title: 'Intermittent Fasting: The Complete Guide',
    category: 'Nutrition',
    type: 'Guide',
    level: 'All',
    duration: '11 min read',
    blurb: '16:8, OMAD, 5:2 — what the science says, who it suits, and how to start without wrecking your training.',
    body: `Intermittent fasting (IF) is an eating pattern, not a diet. You cycle between eating and fasting windows. The benefit isn\'t magic — it\'s mostly that you eat less when you have less time to do it.\n\nCOMMON PROTOCOLS\n- 16:8 — fast 16h, eat within 8h (e.g. noon-8pm). Most popular, sustainable.\n- 14:10 — easier entry for women or beginners.\n- OMAD — one meal a day. Extreme, not for everyone.\n- 5:2 — eat normally 5 days, 500-600 kcal on 2 non-consecutive days.\n- Alternate-day fasting — research-backed but hard.\n\nWHAT BREAKS A FAST\n- Anything with calories (food, juice, milk, sugar).\n- Black coffee, plain tea, water, salt — fine.\n- A splash of milk? Technically yes, but for general health goals it won\'t matter.\n\nBENEFITS (evidence-backed)\n- Easier calorie control = fat loss.\n- Lower insulin levels (helps fat oxidation).\n- Some autophagy (cellular cleanup) — but you need longer fasts (24h+) for meaningful effects.\n- Simpler day — fewer meals to plan.\n\nHOW TO START\n1. Pick a window: 12pm-8pm is the easiest 16:8.\n2. Hydrate in the morning — water, black coffee, salt.\n3. Break fast with protein + whole foods, not junk.\n4. Eat normally in your window — don\'t binge.\n5. Train during your eating window if possible (energy + recovery).\n\nFOR LIFTERS\n- Fasted training is fine for low-intensity. Heavy lifting fasted can suffer.\n- Best: train 1-2h after your first meal, eat protein right after.\n- Hit your daily protein target (1.6-2.2g/kg) within your window.\n- If strength drops, shorten the fast (14:10) or shift the window.\n\nWHO SHOULD SKIP IF\n- Underweight, pregnant, breastfeeding, history of eating disorders, type 1 diabetes (without doctor supervision).\n- Kids and teens still growing.\n\nIF is a tool. If it fits your life, use it. If it makes you miserable or hurts your lifts, eat normally. Consistency beats the perfect protocol.`,
    free: true,
  },
  {
    id: 'r30',
    title: 'Sleep Optimization: 12 Levers for Deeper Rest',
    category: 'Recovery',
    type: 'Guide',
    level: 'All',
    duration: '12 min read',
    blurb: 'Sleep is the most anabolic thing you can do. 12 evidence-based levers to sleep deeper, longer and wake up sharper.',
    body: `Sleep is when growth hormone peaks, muscle repairs, memories consolidate and the CNS resets. Skimping it sabotages every rep and every meal. Here are 12 levers — start with the top 4.\n\nTIER 1: THE BIG FOUR (do these first)\n1. FIXED SCHEDULE — same bed/wake time, even weekends. Sets your circadian rhythm.\n2. MORNING SUNLIGHT — 10 min outside within 30 min of waking. Anchors your body clock.\n3. COOL, DARK, QUIET ROOM — 18-20°C, blackout curtains, earplugs or white noise.\n4. NO SCREENS 60 MIN BEFORE BED — blue light suppresses melatonin. Read a book instead.\n\nTIER 2: HIGH-IMPACT HABITS\n5. LAST MEAL 2-3H BEFORE BED — lower carbs, higher protein. Heavy late meals disrupt deep sleep.\n6. CUT CAFFEINE AT 2PM — half-life is 5-6 hours; even if you fall asleep, sleep quality drops.\n7. LIMIT ALCOHOL — it knocks you out but destroys REM sleep. You\'ll wake groggy.\n8. PRE-BED WIND-DOWN — same ritual every night (shower, read, stretch). Signals "sleep mode".\n\nTIER 3: FINE-TUNING\n9. MAGNESIUM GLYCINATE 200-400mg, 30 min before bed (if deficient — sleep, cramps, recovery).\n10. HOT SHOWER BEFORE BED — body temp drops after, which signals sleep.\n11. LIMIT FLUIDS 90 MIN BEFORE BED — wake-ups kill deep sleep.\n12. GET UP IF YOU CAN\'T SLEEP — don\'t lie there frustrated. Read under dim light for 15 min, then try again.\n\nTRACKING\n- Aim 7-9h. If you wake without an alarm feeling rested, you\'re there.\n- Track HRV (Oura, Whoop, Apple Watch) if you want data. Trend matters more than one night.\n- One bad night won\'t kill gains. Chronic deficit will.\n\nYOUR BODY BUILDS IN BED, NOT IN THE GYM. Protect your sleep like your training.`,
    free: true,
  },
  {
    id: 'r31',
    title: 'Foam Rolling: The Complete Guide',
    category: 'Mobility',
    type: 'Guide',
    level: 'All',
    duration: '8 min read',
    blurb: 'Self-myofascial release made simple — what to roll, how long, how hard, and what it actually does (and doesn\'t) do.',
    body: `Foam rolling (self-myofascial release) applies pressure to muscles and connective tissue to reduce stiffness, improve blood flow and feel better. It\'s not a miracle — but it works.\n\nWHAT IT DOES\n- Short-term flexibility/range of motion boost (5-10 min post-roll).\n- Reduces DOMS when used after hard sessions.\n- Increases blood flow to the area.\n- Calms the nervous system (slow rolls).\n\nWHAT IT DOESN\'T DO\n- Doesn\'t "break up adhesions" or "release fascia" (that takes way more force).\n- Doesn\'t replace stretching or mobility work.\n- Doesn\'t build muscle or burn fat.\n\nHOW TO ROLL\n- Slow: 1-2 cm per second. Fast rolling does nothing.\n- Pressure: 6-7/10 discomfort. Not agony.\n- Duration: 30-60s per spot, 2-3 passes per muscle.\n- Breathe deep — exhale on the tender spots.\n- Never roll joints, lower back (use a ball instead), or bones.\n\nKEY AREAS TO ROLL\n1. QUADS — front of thigh. Most-used, most-tight.\n2. HAMSTRINGS — back of thigh.\n3. CALVES — sit on floor, cross other leg on top for more pressure.\n4. IT BAND — side of thigh (this one hurts; gentle pressure).\n5. GLUTES — sit on roller, cross ankle over knee.\n6. UPPER BACK (THORACIC) — hands behind head, support neck, roll slowly.\n7. LATS — side-lying, roll from armpit to hip.\n8. CHEST — use a ball against a wall for the pecs.\n\nWHEN TO ROLL\n- Pre-workout: 5 min, light and quick. Wakes up tissue.\n- Post-workout: 5-10 min, slower and deeper. Aids recovery.\n- Off-day: 15-20 min full-body maintenance.\n\nBEST PRACTICES\n- Hydrate — tissue slides better when hydrated.\n- Consistent 5 min daily beats 30 min weekly.\n- Sore? Back off. Sharp pain? Stop.\n- Don\'t roll a freshly-injured area (first 48-72h).\n\nFoam rolling is the cheapest recovery tool you own. Use it daily for 5-10 min and your body will move noticeably better in 2-3 weeks.`,
    free: true,
  },
  {
    id: 'r32',
    title: 'Overhead Press Technique: Press Like a Pro',
    category: 'Strength',
    type: 'Guide',
    level: 'Intermediate',
    duration: '10 min read',
    blurb: 'Build boulder shoulders and a strong press: setup, brace, bar path, breathing. The definitive OHP guide.',
    body: `The overhead press (OHP) is the truest test of upper-body strength. It also reveals every weakness in your setup. Master these cues and watch your numbers climb.\n\nSETUP\n1. Stance shoulder-width, feet planted (no wider).\n2. Grip just outside shoulder width, elbows slightly in front of the bar.\n3. Bar racked on the "shelf" of your front delts and upper chest.\n4. Forearms vertical from the side — straight up and down.\n5. Squeeze glutes and brace core hard (this protects your lower back).\n\nEXECUTION\n1. Big breath, brace.\n2. Press straight up — the bar should travel in a vertical line over the middle of your foot.\n3. As the bar passes your nose, push your head and torso "through" — move your head forward and under the bar.\n4. Lock out overhead with bar over your ears (or slightly behind).\n5. Shrug the traps slightly at the top for shoulder health (scapular elevation = stable joint).\n6. Lower under control to the chest — don\'t bounce.\n\nBREATHING\n- Inhale and brace at the bottom (chest level).\n- Hold the breath through the press and lockout.\n- Exhale and re-brace at the bottom for the next rep.\n- Holding your breath keeps your torso rigid — essential for a heavy press.\n\nCOMMON MISTAKES\n- LEANING BACK — turns the press into an incline press and strains the lower back. Squeeze glutes, brace hard, stay vertical.\n- BAR PATH AROUND THE HEAD — the bar should go straight up. Move your head back, then forward — not the bar.\n- FLARED ELBOWS — stress on the shoulder joint. Elbows in front of the bar.\n- BOUNCING OFF THE CHEST — kills tension and risks injury. Pause briefly at the bottom.\n- LOSING BRACE MID-SET — re-brace every rep if needed.\n\nPROGRAMMING\n- Train 2x/week: one heavy (5x5) and one volume (4x8-10).\n- Progress slowly — OHP is the slowest of the big lifts to improve.\n- Pair with pulling (rows, pull-ups) for balanced shoulders.\n- Add accessory work: lateral raises, face pulls, z-press.\n\nIf your press stalls, the issue is almost always leg drive/core stability, not shoulder strength. Film yourself from the side. The bar should move in a straight vertical line over mid-foot.`,
    free: true,
  },
  {
    id: 'r33',
    title: 'Bulgarian Split Squat: The Quad Builder',
    category: 'Strength',
    type: 'Drill',
    level: 'Intermediate',
    duration: '8 min',
    blurb: 'Single-leg strength, quad hypertrophy, hip stability — the split squat builds legs that squat can\'t.',
    body: `The Bulgarian split squat (rear-foot elevated split squat) is one of the most demanding and rewarding leg exercises. It builds single-leg strength, fixes imbalances, taxes the quads and glutes, and saves the lower back.\n\nSETUP\n1. Stand with back to a bench (knee-height).\n2. Place top of rear foot on the bench (laces down for comfort).\n3. Walk front foot forward so when you descend, front knee tracks over the ankle at ~90°.\n4. Front foot flat, weight mostly through the heel and mid-foot.\n\nEXECUTION\n1. Brace, torso upright (slight forward lean targets glutes more).\n2. Descend under control — drop the back knee toward the floor.\n3. Stop when front thigh is parallel to floor (or deeper if mobility allows).\n4. Drive through the front heel to stand back up.\n5. Squeeze glute at the top. That\'s one rep.\n\nCUES\n- "Tall torso" — keeps the work in the quads.\n- "Knee tracks over toes" — don\'t let it cave inward.\n- "Front heel drives" — power comes from the front leg.\n- "Back leg is just a kickstand" — minimal weight on the rear foot.\n\nVARIATIONS BY GOAL\n- QUAD FOCUS: front foot closer to bench, torso upright.\n- GLUTE FOCUS: front foot further forward, slight torso lean, drive through heel.\n- LOADED: goblet (light), dumbbells (medium), barbell (heavy).\n- DEFICIT: front foot on a small plate for deeper range.\n\nPROGRAMMING\n- 3-4 sets of 8-12 reps per side.\n- Start bodyweight to nail form, then add load.\n- Train 1-2x/week as accessory to squats or as a main lift.\n- Progress slowly — this exercise is humbling. Don\'t ego-load.\n\nCOMMON ISSUES\n- BACK FOOT CRAMPING — try a foam pad under the foot, or rest the instep instead of laces.\n- FRONT KNEE PAIN — check foot position (closer = harder on knee). Don\'t let knee dive past toes excessively.\n- CAN\'T BALANCE — use a wall or rack for a finger-tap until you build stability.\n- LOWER BACK STRAIN — usually from leaning too far forward. Stay tall.\n\nDo these consistently for 8 weeks and you\'ll feel it every time you climb stairs — and your squat and deadlift will move up too.`,
    free: true,
  },
  {
    id: 'r34',
    title: 'Intermittent Fasting for Fat Loss',
    category: 'Fat Loss',
    type: 'Guide',
    level: 'Intermediate',
    duration: '9 min read',
    blurb: 'How to use IF specifically for fat loss — window timing, training fasted, breaking the fast, and avoiding pitfalls.',
    body: `Intermittent fasting (IF) is a powerful fat-loss tool because it makes eating less easier. But to lose fat (not muscle) while training hard, you need to do it right.\n\nWHY IF WORKS FOR FAT LOSS\n- Spontaneous calorie reduction — fewer meals = fewer calories, without tracking.\n- Lower insulin during the fast — easier fat oxidation.\n- Discipline muscle — saying "no" to the morning snack builds grit.\n- Simpler day — fewer food decisions = less decision fatigue.\n\nPICK YOUR WINDOW\n- 16:8 (most popular) — eat noon to 8pm. Skip breakfast, eat lunch + dinner + small snack.\n- 14:10 (easier, better for women) — eat 10am to 8pm.\n- 20:4 (aggressive) — eat 4pm to 8pm. Two large meals.\n\nTRAINING WHILE FASTED\n- Low-intensity cardio (walking, easy cycling) — fine fasted, even beneficial for fat oxidation.\n- HIIT/conditioning — possible but performance drops. Eat a small pre-meal if needed.\n- Heavy lifting fasted — works for some, destroys others. Try it; if strength drops, shift training to after your first meal.\n- BEST: train 1-2h after your first meal, eat a high-protein meal right after.\n\nHOW TO BREAK THE FAST\n- Don\'t break with junk. First meal should be high-protein + whole foods.\n- Examples: eggs + avocado + veg, chicken + rice + salad, whey + banana + nuts.\n- Avoid a huge sugar/fat bomb — you\'ll crash and overeat the rest of the day.\n\nMACROS IN YOUR WINDOW\n- Protein: 2.0-2.4g/kg (high — protects muscle in a deficit).\n- Carbs: train-day carbs around training; rest-day lower.\n- Fats: 0.6-0.8g/kg.\n- Total: 300-500kcal deficit. IF doesn\'t override thermodynamics.\n\nCOMMON MISTAKES\n- BINGEING IN THE WINDOW — "I fasted 16h, I can eat whatever." No. You\'ll still gain weight.\n- NOT EATING ENOUGH PROTEIN — easier to forget when you have fewer meals. Track it.\n- OVER-CAFFEINATING — coffee curbs hunger but ruins sleep. Cap at 2-3 cups before noon.\n- USING IF TO EXCUSE BAD FOOD — fasted window ≠ free pass for junk.\n- DOING IT FOREVER — IF is a tool. Cycle in maintenance breaks every 8-12 weeks.\n\nSIGNS IT\'S NOT WORKING\n- Strength dropping hard — shorten fast, add protein.\n- Sleep issues — eat your last meal earlier, don\'t train too late fasted.\n- Hormonal issues (especially women) — switch to 14:10 or stop.\n- Miserable, obsessing over food — not worth it. Eat normally.\n\nIF is one of many paths to fat loss. The best protocol is the one you can stick to. If 16:8 fits your life, run it. If not, find your own way.`,
    free: true,
  },
  {
    id: 'r35',
    title: 'Grip Strength Training: Build Iron Hands',
    category: 'Strength',
    type: 'Guide',
    level: 'All',
    duration: '10 min read',
    blurb: 'Strong hands lift more, hold longer, and prevent injuries. The four types of grip and how to train each.',
    body: `Grip is the weakest link in most lifters\' chains. Deadlift stalls? Often grip. Pull-ups plateau? Grip. Farmer carries humbling? Grip. Train it directly and everything else goes up.\n\nTHE 4 TYPES OF GRIP\n1. CRUSH — closing your hand (handshake, gripper).\n2. PINCH — thumb + fingers pinching together (plate pinch).\n3. SUPPORT — holding a heavy load over time (deadlift, farmer carry).\n4. EXTENSION — opening the hand (rubber band extensions).\n\nA balanced program trains all four.\n\nEXERCISES BY TYPE\n\nCRUSH\n- CAPTAINS OF CRUSH GRIPPERS: 3-5 sets of 5-8 reps, 2-3x/week. Progress to harder grippers.\n- TOWEL CRUSH: roll a towel and squeeze in your fist, hold 10s. 3 sets.\n- WRIST CURLER: rope + weight on a stick, roll up and down. 3 sets.\n\nPINCH\n- PLATE PINCH: pinch two smooth plates (5kg or 10kg) together by the edges. Hold 20-30s, 3 sets.\n- PINCH BLOCK CARRY: carry a pinched block for distance.\n\nSUPPORT\n- FARMER\'S CARRY: heavy dumbbells, walk 20-30m. 3-4 sets. The king of grip work.\n- DEAD HANG: from pull-up bar, build to 60s+.\n- RACK PULLS HEAVIER THAN DEADLIFT: overload grip with straps off.\n- STATIC BARBELL HOLD: hold loaded bar at top of deadlift for 10-20s.\n\nEXTENSION (often neglected — prevents imbalance)\n- RUBBER BAND EXTENSIONS: band around fingers, open hand. 3 sets of 15-20.\n- RICE BUCKET: open and close hand in a rice bucket. 3 sets of 20.\n\nPROGRAMMING\n- 2-3 short sessions per week (10-15 min each).\n- Train at the END of your workout, never before — fatigued grip ruins pulling lifts.\n- Progress slow — tendons adapt slower than muscles. Add load every 2-3 weeks.\n- Mix types — don\'t just train crush.\n\nGRIP FOR DEADLIFT\n- Try double-overhand as long as possible. When it fails, switch to hook grip (thumbs under fingers) before mixed grip.\n- Train grip directly and your double-overhand will go up — that\'s the metric that matters.\n- Use straps only for top sets if grip is the limit, but always do rep work strapless.\n\nFOREARMS\nForearms grow from heavy grip work — you don\'t need much isolation. But if you want extra: wrist curls, reverse wrist curls, and reverse curls 2x/week for 3 sets of 12-15.\n\nSAMPLE WEEK\n- MON (after pull day): grippers 3x6 + plate pinch 3x30s.\n- WED (after leg day): farmer carry 4x30m + dead hang 3x45s.\n- FRI (after push day): wrist curler 3x10 + rubber band extensions 3x20.\n\nIn 12 weeks your grip will be unrecognizable — and so will your deadlift, pull-ups and carries. Strong hands, strong lift.`,
    free: true,
  },
]
